# code highlining
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=inline"

# Site settings
baseurl = "https://stereobooster.netlify.com/"
# for <html lang={}>
languageCode = "en"
title = "stereobooster personal blog"

[params]
  # twitter:creator
  # <meta name="author">
	author = "stereobooster"
	# twitter:description
	# <meta name="description"
	# description = "Site Description"

	# twitter:site
	twitter = "stereobooster"

	enableRSS = true
	enableToc = false

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

  # googleAnalytics = ""
	# enableGoogleAnalytics = true

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

# Add additional social link entries underneath
[social]
	twitter-link = "https://www.twitter.com/stereobooster"
	github-link = "https://www.github.com/stereobooster"
